import os

TAMANO = 20
RANKING_FILE = "ranking.txt"

paises = [
    "ARGENTINA", "BRASIL", "CANADA", "CHILE", "ALEMANIA", "FRANCIA", "RUSIA", "JAPON", "INDIA", "AUSTRALIA",
    "EGIPTO", "ITALIA", "MEXICO", "URUGUAY", "CUBA", "ESPAÑA", "PORTUGAL", "SUDAFRICA", "NORUEGA", "SUECIA"
]